const plans = [
  {
    id: "1-month",
    duration: "1 Month",
    price: 1500,
    per: "/ mo",
    subprice: "No commitment",
    badge: null,
    featured: false,
    features: [
      { label: "Full gym access", included: true },
      { label: "Locker & shower", included: true },
      { label: "Free weights & machines", included: true },
      { label: "Group classes", included: false },
      { label: "Personal trainer sessions", included: false },
      { label: "Nutrition consultation", included: false },
    ],
  },
  {
    id: "3-month",
    duration: "3 Months",
    price: 4050,
    per: "/ 3 mo",
    subprice: "৳1,350 / month",
    badge: { label: "Save 10%", type: "save" },
    featured: false,
    features: [
      { label: "Full gym access", included: true },
      { label: "Locker & shower", included: true },
      { label: "Free weights & machines", included: true },
      { label: "Group classes (2/week)", included: true },
      { label: "Personal trainer sessions", included: false },
      { label: "Nutrition consultation", included: false },
    ],
  },
  {
    id: "6-month",
    duration: "6 Months",
    price: 7500,
    per: "/ 6 mo",
    subprice: "৳1,250 / month",
    badge: { label: "Save 17%", type: "save" },
    featured: false,
    features: [
      { label: "Full gym access", included: true },
      { label: "Locker & shower", included: true },
      { label: "Free weights & machines", included: true },
      { label: "Group classes (unlimited)", included: true },
      { label: "1 PT session / month", included: true },
      { label: "Nutrition consultation", included: false },
    ],
  },
  {
    id: "9-month",
    duration: "9 Months",
    price: 10350,
    per: "/ 9 mo",
    subprice: "৳1,150 / month",
    badge: { label: "Save 23%", type: "save" },
    featured: false,
    features: [
      { label: "Full gym access", included: true },
      { label: "Locker & shower", included: true },
      { label: "Free weights & machines", included: true },
      { label: "Group classes (unlimited)", included: true },
      { label: "2 PT sessions / month", included: true },
      { label: "1 nutrition consult", included: true },
    ],
  },
  {
    id: "1-year",
    duration: "1 Year",
    price: 12000,
    per: "/ yr",
    subprice: "৳1,000 / month · Save 33%",
    badge: { label: "Most popular", type: "best" },
    featured: true,
    features: [
      { label: "Full gym access", included: true },
      { label: "Locker & shower", included: true },
      { label: "Free weights & machines", included: true },
      { label: "Group classes (unlimited)", included: true },
      { label: "4 PT sessions / month", included: true },
      { label: "Monthly nutrition consult", included: true },
    ],
  },
  {
    id: "lifetime",
    duration: "Lifetime",
    price: 75000,
    per: "once",
    subprice: "Pay once, train forever",
    badge: { label: "Lifetime", type: "life" },
    featured: false,
    features: [
      { label: "Full gym access", included: true },
      { label: "Locker & shower", included: true },
      { label: "Free weights & machines", included: true },
      { label: "Group classes (unlimited)", included: true },
      { label: "Unlimited PT sessions", included: true },
      { label: "Weekly nutrition consult", included: true },
    ],
  },
];

export default plans;
